# Generated by Django 2.1.7 on 2019-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_foodname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodname',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
