# Generated by Django 2.1.5 on 2019-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20190401_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodname',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
